### ISSUE TITLE
Mobile search is broken

### ISSUE THREAD

**Issue by he3als** [hummingbot/hummingbot-site#266]
Due to the blurred header in the CSS, the mobile search displays no results. I've found a hacky workaround for this:

```css
/* Fix mobile search with blurred header 
   Causes a delay when opening search, not optimal */
[data-md-scrolllock] .md-header,
[data-md-scrolllock] .md-tabs {
    -webkit-backdrop-filter: none !important;
    backdrop-filter: none !important;
}
```
